# Generated by Django 5.0.1 on 2026-03-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CameraFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mess_id",
                    models.IntegerField(
                        help_text="Mess ID (FK to mess app once available)"
                    ),
                ),
                (
                    "camera_url",
                    models.URLField(
                        help_text="RTSP or HTTP stream URL", max_length=500
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("location_description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Camera Feed",
                "verbose_name_plural": "Camera Feeds",
            },
        ),
        migrations.CreateModel(
            name="CrowdMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mess_id", models.IntegerField(help_text="Mess ID")),
                ("density_percentage", models.FloatField()),
                ("estimated_count", models.IntegerField()),
                (
                    "density_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estimated_wait_minutes", models.FloatField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Crowd Metric",
                "verbose_name_plural": "Crowd Metrics",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["mess_id", "-recorded_at"],
                        name="crowd_crowd_mess_id_65799d_idx",
                    )
                ],
            },
        ),
    ]
