# Generated by Django 5.0.1 on 2026-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("mess_manager", "Mess Manager"),
                    ("mess_worker", "Mess Worker"),
                    ("canteen_manager", "Canteen Manager"),
                    ("delivery_person", "Delivery Person"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
