# Generated by Django 5.0.1 on 2026-04-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0001_initial"),
        ("users", "0004_alter_role_role_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="canteen_id",
        ),
        migrations.AddField(
            model_name="staff",
            name="canteen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="canteen.canteen",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="hostel_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hall_1", "Hall 1"),
                    ("hall_2", "Hall 2"),
                    ("hall_3", "Hall 3"),
                    ("hall_4", "Hall 4"),
                    ("hall_5", "Hall 5"),
                    ("hall_7", "Hall 7"),
                    ("hall_8", "Hall 8"),
                    ("hall_9", "Hall 9"),
                    ("hall_10", "Hall 10"),
                    ("hall_11", "Hall 11"),
                    ("hall_12", "Hall 12"),
                    ("hall_13", "Hall 13"),
                    ("hall_14", "Hall 14"),
                    ("gh_1", "Girls Hostel 1"),
                    ("ght_2", "Girls Hostel Tower 2"),
                ],
                max_length=100,
            ),
        ),
    ]
