# Generated by Django 5.0.1 on 2026-04-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_student_hostel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="hostel_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
