# Generated by Django 5.0.1 on 2026-03-22 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Canteen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("location", models.CharField(max_length=200)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("is_delivery_available", models.BooleanField(default=True)),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rating",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="canteen_can_is_acti_c6af4c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CanteenMenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=80)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canteen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="canteen.canteen",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "category_name"],
            },
        ),
        migrations.CreateModel(
            name="CanteenMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("preparation_time_mins", models.PositiveSmallIntegerField(default=10)),
                ("is_veg", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("available_quantity", models.PositiveIntegerField(default=0)),
                ("image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canteen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="canteen.canteen",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="canteen.canteenmenucategory",
                    ),
                ),
            ],
            options={
                "ordering": ["item_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="canteenmenucategory",
            constraint=models.UniqueConstraint(
                fields=("canteen", "category_name"), name="uniq_canteen_category_name"
            ),
        ),
        migrations.AddIndex(
            model_name="canteenmenuitem",
            index=models.Index(
                fields=["canteen", "is_active", "is_available"],
                name="canteen_can_canteen_98acc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="canteenmenuitem",
            index=models.Index(fields=["is_veg"], name="canteen_can_is_veg_8dc884_idx"),
        ),
    ]
