# Generated by Django 5.0.1 on 2026-04-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canteen",
            name="closing_time",
        ),
        migrations.RemoveField(
            model_name="canteen",
            name="opening_time",
        ),
    ]
