# Generated by Django 5.0.1 on 2026-04-02 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0002_remove_canteen_closing_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanteenPaymentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upi_id", models.CharField(blank=True, max_length=120)),
                ("qr_image_url", models.URLField(blank=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("cash", "Cash"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canteen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_config",
                        to="canteen.canteen",
                    ),
                ),
            ],
        ),
    ]
