# Generated by Django 5.0.1 on 2026-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0003_canteenpaymentconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canteenpaymentconfig",
            name="qr_image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
