# Generated by Django 5.0.14 on 2026-03-21 13:03

import apps.mess.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=255)),
                ('hall_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('default_quantity', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='mess.mess')),
            ],
            options={
                'ordering': ['mess__name', 'day_of_week', 'meal_type', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='MessBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('booking_date', models.DateField(default=django.utils.timezone.localdate)),
                ('qr_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('qr_generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_expires_at', models.DateTimeField(default=apps.mess.models.default_qr_expiry)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redeemed_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_mess_bookings', to='users.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mess_bookings', to='users.student')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='mess.messmenuitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(choices=[('manager', 'Manager'), ('worker', 'Worker')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='mess.mess')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_assignments', to='users.staff')),
            ],
            options={
                'ordering': ['mess__name', 'assignment_role', 'staff__full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='messmenuitem',
            constraint=models.UniqueConstraint(fields=('mess', 'item_name', 'meal_type', 'day_of_week'), name='uq_mess_menuitem_per_mess_day_meal_name'),
        ),
        migrations.AddConstraint(
            model_name='messmenuitem',
            constraint=models.CheckConstraint(check=models.Q(('available_quantity__gte', 0)), name='ck_mess_menuitem_available_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='messmenuitem',
            constraint=models.CheckConstraint(check=models.Q(('default_quantity__gte', 0)), name='ck_mess_menuitem_default_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='messbooking',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='ck_mess_booking_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='messbooking',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='ck_mess_booking_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='messstaffassignment',
            constraint=models.UniqueConstraint(fields=('staff', 'mess', 'assignment_role'), name='uq_mess_staff_assignment_role'),
        ),
    ]
