# Generated by Django 5.0.1 on 2026-04-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mess", "0002_alter_mess_hall_name_alter_mess_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mess",
            name="hall_name",
            field=models.CharField(
                choices=[
                    ("hall_1", "Hall 1"),
                    ("hall_2", "Hall 2"),
                    ("hall_3", "Hall 3"),
                    ("hall_4", "Hall 4"),
                    ("hall_5", "Hall 5"),
                    ("hall_6", "Hall 6"),
                    ("hall_7", "Hall 7"),
                    ("hall_8", "Hall 8"),
                    ("hall_9", "Hall 9"),
                    ("hall_10", "Hall 10"),
                    ("hall_11", "Hall 11"),
                    ("hall_12", "Hall 12"),
                    ("hall_13", "Hall 13"),
                    ("hall_14", "Hall 14"),
                    ("gh_1", "Girls Hostel 1"),
                    ("ght_2", "Girls Hostel Tower 2"),
                ],
                max_length=120,
                unique=True,
            ),
        ),
    ]
