# Generated by Django 5.0.1 on 2026-04-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mess", "0003_alter_mess_hall_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mess",
            name="hall_name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
